spring.application.name=labor-cost-bot

spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterAccess=1d

server.port=51001

telegram.bot.token=${BOT_TOKEN}
telegram.bot.telegram-user-id=${TG_USER_ID}

portal.credentials.username=${PORTAL_LOGIN}
portal.credentials.password=${PORTAL_PASSWORD}

client.configuration.connection-timeout=10s
client.configuration.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36

data.storage=/data